### ISSUE TITLE
What happens if a connection drops without a RST or FIN?

### ISSUE THREAD

**Issue by xymb-endcrystalme** [xymb-endcrystalme/LimboPaper#1]
> oh you just deleted keepalive logic, what happens if a connection drops without a RST or FIN?
> that's literally a DoS attack right there

`ServerPlayer.doTick()`

**Comment by XionioXMaster** [comment]
bruuuuuh

**Comment by XionioXMaster** [comment]
by the way, did you use the plugin on bots or just a flooder?

**Comment by xymb-endcrystalme** [comment]
I used these ones: https://github.com/PureGero/minecraft-stress-test
