### ISSUE TITLE
Players can still break blocks, even with protection from WorldGuard

### ISSUE THREAD

**Issue by BasToTheMax** [xymb-endcrystalme/LimboPaper#3]

**Comment by xymb-endcrystalme** [comment]
LimboPaper completely ignores movement and breaking blocks packets from the client, so neither WorldGuard nor the server nor any other players know that the block was broken. It just _looks_ like blocks were broken, but it's only a client-side rendering issue.

Don't use WorldGuard with LimboPaper, it's pointless. Just set players to "adventure mode", this way they'll have no ability to break blocks even on the client-side.

**Comment by BasToTheMax** [comment]
👍
